apiVersion: v1
kind: Service
metadata:
  name: chipin-service
  namespace: chipin
  labels:
    app.kubernetes.io/name: chipin-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chipin-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
